version: 2.1
jobs:
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d5:4c:ce:d1:bc:f6:63:7c:ac:41:d4:eb:d1:b5:b6:86"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/antismoking/ && git pull'

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
