version: 2.1
jobs:
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "af:dc:00:c0:3c:81:df:33:52:3a:9a:c6:ea:2c:03:d9"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/antismoking/ && git pull'

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
